namespace DeadworksManaged.Api;

/// <summary>Source 2 console variable / console command flags, as the engine's tier0 names them.</summary>
[Flags]
public enum FCVar : ulong
{
    None = 0,

    /// <summary>Allows command callback chaining: when the command is dispatched, every chained callback fires.</summary>
    LinkedConCommand = 1UL << 0,
    /// <summary>Hidden in released products. Removed automatically if ALLOW_DEVELOPMENT_CVARS is defined.</summary>
    DevelopmentOnly = 1UL << 1,
    /// <summary>Defined by the game DLL.</summary>
    GameDll = 1UL << 2,
    /// <summary>Defined by the client DLL.</summary>
    ClientDll = 1UL << 3,
    /// <summary>Hidden. Doesn't appear in find or auto complete. Like DevelopmentOnly, but can't be compiled out.</summary>
    Hidden = 1UL << 4,

    /// <summary>ConVar only: it's a server cvar, but the data isn't sent because it's a password etc.</summary>
    Protected = 1UL << 5,
    /// <summary>This cvar cannot be changed by clients connected to a multiplayer server.</summary>
    SpOnly = 1UL << 6,
    /// <summary>Set to cause it to be saved to vars.rc.</summary>
    Archive = 1UL << 7,
    /// <summary>Notifies players when changed.</summary>
    Notify = 1UL << 8,
    /// <summary>Changes the client's info string.</summary>
    UserInfo = 1UL << 9,

    /// <summary>The cvar is a reference to one registered in another module, until that one is registered.</summary>
    Reference = 1UL << 10,
    /// <summary>If this is a server cvar, don't log changes to the log file / console when creating a log.</summary>
    Unlogged = 1UL << 11,
    /// <summary>Set for the first SetValue, with the default or a value from gameinfo. Mostly for callbacks to check.</summary>
    InitialSetValue = 1UL << 12,
    /// <summary>Server setting enforced on clients (ConVar shared between client and server).</summary>
    Replicated = 1UL << 13,
    /// <summary>Only useable in singleplayer / debug / multiplayer with sv_cheats.</summary>
    Cheat = 1UL << 14,
    /// <summary>Causes varnameN where N == 2..max splitscreen slots to be autogenerated.</summary>
    PerUser = 1UL << 15,
    /// <summary>Record this cvar when starting a demo file.</summary>
    Demo = 1UL << 16,
    /// <summary>Don't record this command in demo files.</summary>
    DontRecord = 1UL << 17,
    /// <summary>Set while the cvar runs its change callbacks; a value set during them is queued until they finish.</summary>
    PerformingCallbacks = 1UL << 18,
    /// <summary>The only cvars available to customers.</summary>
    Release = 1UL << 19,
    MenuBarItem = 1UL << 20,
    /// <summary>Set from the launch options, so resetting cvars to their defaults by flag leaves it.</summary>
    CommandLineEnforced = 1UL << 21,

    /// <summary>Cvar cannot be changed by a client that is connected to a server.</summary>
    NotConnected = 1UL << 22,
    VConsoleFuzzyMatching = 1UL << 23,

    /// <summary>The server is allowed to execute this command on clients via ClientCommand / NET_StringCmd / CBaseClientState::ProcessStringCmd.</summary>
    ServerCanExecute = 1UL << 24,
    /// <summary>Clients may execute this command.</summary>
    ClientCanExecute = 1UL << 25,
    /// <summary>If set, the server is not allowed to query this cvar's value (via IServerPluginHelpers::StartQueryCvarValue).</summary>
    ServerCannotQuery = 1UL << 26,
    VConsoleSetFocus = 1UL << 27,
    /// <summary>IVEngineClient::ClientCmd is allowed to execute this command. (ClientCmd_Unrestricted runs any.)</summary>
    ClientCmdCanExecute = 1UL << 28,
    ExecutePerTick = 1UL << 29,

    Defensive = 1UL << 32,
}
