using System.Text;

namespace DeadworksManaged.GameGen;

static class Naming {
	private static readonly HashSet<string> Keywords = [
		"abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
		"decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
		"fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
		"long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected",
		"public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
		"struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
		"using", "virtual", "void", "volatile", "while",
	];

	/// <summary>
	/// The game's name as a C# identifier: kept as it is where it already is one, with
	/// <c>::</c> as <c>__</c>, any other character as <c>_</c>, and a keyword escaped with <c>@</c>.
	/// </summary>
	public static string Identifier(string name) {
		var sb = new StringBuilder(name.Length + 2);
		foreach (char c in name.Replace("::", "__"))
			sb.Append(char.IsAsciiLetterOrDigit(c) || c == '_' ? c : '_');
		if (sb.Length == 0 || char.IsAsciiDigit(sb[0])) sb.Insert(0, '_');
		string identifier = sb.ToString();
		return Keywords.Contains(identifier) ? "@" + identifier : identifier;
	}

	/// <summary>True if the name is a C# identifier as it stands.</summary>
	public static bool IsIdentifier(string name)
		=> name.Length > 0 && !char.IsAsciiDigit(name[0]) && name.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');

	/// <summary><paramref name="identifier"/>, with underscores appended until <paramref name="taken"/> does not have it; then recorded there.</summary>
	public static string Unique(string identifier, HashSet<string> taken) {
		while (!taken.Add(identifier)) identifier += "_";
		return identifier;
	}

	public static string Literal(string text) => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

	/// <summary>Text for an XML doc comment, on one line.</summary>
	public static string Doc(string text) => string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries))
		.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

	/// <summary>The dump quotes metadata strings; this takes the quotes off.</summary>
	public static string Unquote(string? value) {
		value = value?.Trim() ?? "";
		return value.Length >= 2 && value[0] == '"' && value[^1] == '"' ? value[1..^1].Replace("\\\"", "\"") : value;
	}
}

/// <summary>Builds one generated C# file with tab indentation.</summary>
sealed class CodeWriter {
	private readonly StringBuilder _sb = new();
	private int _indent;

	public const string Header = "// <auto-generated>\n// Generated by DeadworksManaged.GameGen from the Deadworks modding database (https://deadworks.net/db). Do not edit.\n// </auto-generated>\n#nullable enable\n";

	public CodeWriter(params string[] usings) {
		_sb.Append(Header);
		foreach (var u in usings) _sb.Append("using ").Append(u).Append(";\n");
		_sb.Append("\nnamespace DeadworksManaged.Game;\n\n");
	}

	public CodeWriter Line(string text = "") {
		if (text.Length > 0) _sb.Append('\t', _indent).Append(text);
		_sb.Append('\n');
		return this;
	}

	public CodeWriter Open(string text) {
		Line(text + " {");
		_indent++;
		return this;
	}

	public CodeWriter Close() {
		_indent--;
		return Line("}");
	}

	public CodeWriter Summary(string text) => text.Length == 0 ? this : Line($"/// <summary>{text}</summary>");

	public override string ToString() => _sb.ToString();
}

/// <summary>
/// The generated directory as a whole: files are written only when their content changes,
/// and a file no emitter produced this run is deleted, so the directory always matches the dump.
/// </summary>
sealed class OutputSet(string root) {
	private readonly Dictionary<string, string> _files = new(StringComparer.OrdinalIgnoreCase);

	public int Count => _files.Count;

	public void Add(string relativePath, string content) {
		if (!_files.TryAdd(relativePath, content))
			throw new InvalidOperationException($"Two generated files map to {relativePath}; names that differ only by case need a distinct file name.");
	}

	/// <summary>A file name for <paramref name="name"/> that no other name in <paramref name="taken"/> has, ignoring case.</summary>
	public static string FileName(string name, HashSet<string> taken) {
		string file = name.Replace("::", "__");
		while (!taken.Add(file.ToLowerInvariant())) file += "_";
		return file;
	}

	public (int Written, int Deleted) Flush() {
		int written = 0, deleted = 0;
		Directory.CreateDirectory(root);
		var keep = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
		foreach (var (relative, content) in _files) {
			string path = Path.Combine(root, relative);
			keep.Add(Path.GetFullPath(path));
			// A checkout with core.autocrlf has CRLF on disk for the same content.
			if (File.Exists(path) && File.ReadAllText(path).Replace("\r\n", "\n") == content) continue;
			Directory.CreateDirectory(Path.GetDirectoryName(path)!);
			File.WriteAllText(path, content, new UTF8Encoding(false));
			written++;
		}
		foreach (var existing in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)) {
			if (keep.Contains(Path.GetFullPath(existing))) continue;
			File.Delete(existing);
			deleted++;
		}
		return (written, deleted);
	}
}
